/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Record({ 'id' : IDL.Int, 'name' : IDL.Text });
export const Product = IDL.Record({
  'id' : IDL.Int,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CartItem = IDL.Record({
  'productId' : IDL.Int,
  'quantity' : IDL.Int,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'canceled' : IDL.Null,
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Int,
  'status' : OrderStatus,
  'total' : IDL.Float64,
  'userId' : IDL.Principal,
  'address' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(CartItem),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
      [IDL.Int],
      [],
    ),
  'addToCart' : IDL.Func([IDL.Int, IDL.Int], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bootstrapAdmin' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'checkout' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Int],
      [],
    ),
  'clearCart' : IDL.Func([], [], []),
  'createCategories' : IDL.Func([IDL.Vec(Category)], [], []),
  'createInitialMarketplace' : IDL.Func(
      [IDL.Vec(Product), IDL.Vec(Category)],
      [IDL.Bool],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Int], [], []),
  'editProduct' : IDL.Func(
      [IDL.Int, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllProductsSortedById' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Int], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getProductsByCategorySortedByPrice' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Record({ 'id' : IDL.Int, 'name' : IDL.Text });
  const Product = IDL.Record({
    'id' : IDL.Int,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CartItem = IDL.Record({ 'productId' : IDL.Int, 'quantity' : IDL.Int });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'canceled' : IDL.Null,
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Int,
    'status' : OrderStatus,
    'total' : IDL.Float64,
    'userId' : IDL.Principal,
    'address' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(CartItem),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
        [IDL.Int],
        [],
      ),
    'addToCart' : IDL.Func([IDL.Int, IDL.Int], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bootstrapAdmin' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'checkout' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Int],
        [],
      ),
    'clearCart' : IDL.Func([], [], []),
    'createCategories' : IDL.Func([IDL.Vec(Category)], [], []),
    'createInitialMarketplace' : IDL.Func(
        [IDL.Vec(Product), IDL.Vec(Category)],
        [IDL.Bool],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Int], [], []),
    'editProduct' : IDL.Func(
        [IDL.Int, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllProductsSortedById' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Int], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByCategorySortedByPrice' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };